server:
  port: 8090

spring:
  application:
    name: fin-compliance-center
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}

logging:
  level:
    com.fin: DEBUG
